# -*- coding: utf-8 -*-
"""CSE427_colab file[pre-processing + Model].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU96gM-hbgpZQxsr5gFm5EUb45aXi9qE

### Pre-processing
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.utils import resample

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler

import lightgbm as lgb

import warnings
warnings.filterwarnings('ignore')

# read dataset from a Google Drive File

file_link = 'https://drive.google.com/file/d/1vacaLMl8VellyUTZM89T9orRFPj8-0zy/view?usp=sharing' # the file access must have to be Public

# get the id part of the file
id = file_link.split("/")[-2]

# creating a new link using the id so that we can easily read the csv file in pandas
new_link = f'https://drive.google.com/uc?id={id}'
print(new_link)
df = pd.read_csv(new_link)

#drop useless coloumn
df.drop(columns=["Unnamed: 0.1", "Unnamed: 0", "uri"], inplace=True)
df = df.drop(columns=['uri'], errors='ignore')

#drop duplicats
df = df.drop_duplicates()

FEATURES = [
    "duration (ms)", "danceability", "energy", "loudness",
    "speechiness", "acousticness", "instrumentalness",
    "liveness", "valence", "tempo", "spec_rate"
]
TARGET = "labels"

X = df[FEATURES]
y = df[TARGET]

#handle class imbalance

# Plot before
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
y.value_counts().sort_index().plot(kind="bar", ax=axes[0],
    color=sns.color_palette("Set2", 4))
axes[0].set_title("Class Distribution BEFORE Balancing")
axes[0].set_xlabel("Label"); axes[0].set_ylabel("Count")
axes[0].tick_params(axis='x', rotation=0)
print(f"\n Dataset shape: {df.shape}")

# Combine X and y for resampling
df_balanced = pd.concat([X, y], axis=1)

# Find the minority class size
min_class_size = y.value_counts().min()

# Undersample each class to match minority class size
balanced_dfs = []
for label in sorted(y.unique()):
    class_df = df_balanced[df_balanced[TARGET] == label]
    class_df_downsampled = resample(class_df,replace=False,n_samples=min_class_size,random_state=42)
    balanced_dfs.append(class_df_downsampled)

df_balanced = pd.concat(balanced_dfs).reset_index(drop=True)
X = df_balanced[FEATURES]
y = df_balanced[TARGET]

print("\nClass distribution AFTER balancing:")
print(y.value_counts())

# Plot after
y.value_counts().sort_index().plot(kind="bar", ax=axes[1],
    color=sns.color_palette("Set2", 4))
axes[1].set_title("Class Distribution AFTER Balancing")
axes[1].set_xlabel("Label"); axes[1].set_ylabel("Count")
axes[1].tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.show()
print(f"\n Balanced dataset shape: {df_balanced.shape}")

#outlier handling

X_clean = X.copy()
for col in FEATURES:
    Q1 = X_clean[col].quantile(0.25)
    Q3 = X_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    n_outliers = ((X_clean[col] < lower) | (X_clean[col] > upper)).sum()
    pct = n_outliers / len(X_clean) * 100

    # Cap values at bounds
    X_clean[col] = X_clean[col].clip(lower=lower, upper=upper)
    print(f"  {col:<22}: {n_outliers:>6,} outliers ({pct:.2f}%) - capped")

#feature scaling

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_clean),columns=FEATURES)

print("\nAfter scaling — feature statistics:")
print(X_scaled.describe().T[["mean", "std", "min", "max"]].round(4))

#dataset split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

"""### Model Implementation

#Logistic Regression
"""

model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

"""#RANDOM FOREST"""

model_rf = RandomForestClassifier(n_estimators=100,max_depth=10,random_state=42)

model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

"""
# LightGBM"""

model_lgb = lgb.LGBMClassifier(n_estimators=100,learning_rate=0.1, verbose=-1)

model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print("LightGBM Accuracy:", accuracy_score(y_test, y_pred_lgb))

"""#dense neural network"""

!pip install tensorflow

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

model_nn = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(len(np.unique(y_train)), activation='softmax')
])

model_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_nn.fit(
    X_train, y_train,
    epochs=20,
    batch_size=256,
    validation_split=0.2,
    verbose=1
)

loss, acc = model_nn.evaluate(X_test, y_test)
print("Neural Network Accuracy:", acc)

"""#XGBoost"""

!pip install xgboost

import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',
    num_class=len(np.unique(y_train)),
    eval_metric='mlogloss'
)

model_xgb.fit(X_train, y_train)

y_pred_xgb = model_xgb.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

"""#TabNet"""

!pip install pytorch-tabnet

import torch
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import accuracy_score

# Ensure NumPy format
X_train = X_train.values if hasattr(X_train, "values") else X_train
X_test = X_test.values if hasattr(X_test, "values") else X_test
y_train = y_train.values if hasattr(y_train, "values") else y_train
y_test = y_test.values if hasattr(y_test, "values") else y_test

tabnet = TabNetClassifier(
    n_d=16,
    n_a=16,
    n_steps=5,
    gamma=1.5,
    lambda_sparse=1e-4,
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    verbose=1
)

tabnet.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    eval_metric=['accuracy'],
    max_epochs=50,
    patience=10,
    batch_size=1024,
    virtual_batch_size=128
)

y_pred = tabnet.predict(X_test)

ac = accuracy_score(y_test, y_pred)
print("TabNet Accuracy:", ac)

"""#comparision"""

results = {}

results["Logistic Regression"] = accuracy_score(y_test, y_pred_lr)
results["Random Forest"] = accuracy_score(y_test, y_pred_rf)
results["LightGBM"] = accuracy_score(y_test, y_pred_lgb)
results["Neural Network"] = acc
results["XGBoost"] = accuracy_score(y_test, y_pred_xgb)
results["TabNet"] = ac

results_df = pd.DataFrame(list(results.items()), columns=["Model", "Accuracy"])
results_df = results_df.sort_values(by="Accuracy", ascending=False)

print(results_df)

import matplotlib.pyplot as plt

plt.figure()
plt.bar(results_df["Model"], results_df["Accuracy"])
plt.xticks(rotation=45)
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.title("Model Comparison")
plt.tight_layout()
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, average='weighted'),
        "Recall": recall_score(y_true, y_pred, average='weighted'),
        "F1 Score": f1_score(y_true, y_pred, average='weighted')
    }

metrics = {}


metrics["Logistic Regression"] = get_metrics(y_test, y_pred_lr)
metrics["Random Forest"] = get_metrics(y_test, y_pred_rf)
metrics["LightGBM"] = get_metrics(y_test, y_pred_lgb)
metrics["XGBoost"] = get_metrics(y_test, y_pred_xgb)

# Neural Network
y_pred_nn = model_nn.predict(X_test)
y_pred_nn = y_pred_nn.argmax(axis=1)
metrics["Neural Network"] = get_metrics(y_test, y_pred_nn)

# TabNet
metrics["TabNet"] = get_metrics(y_test, y_pred)

# Convert to DataFrame
import pandas as pd
metrics_df = pd.DataFrame(metrics).T

print(metrics_df)

"""confussion matrix"""

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt
# Neural Network
y_pred_nn = model_nn.predict(X_test)
y_pred_nn = y_pred_nn.argmax(axis=1)

# TabNet
y_pred_tabnet = tabnet.predict(X_test)
predictions = {
    "Logistic Regression": y_pred_lr,
    "Random Forest": y_pred_rf,
    "LightGBM": y_pred_lgb,
    "XGBoost": y_pred_xgb,
    "Neural Network": y_pred_nn,
    "TabNet": y_pred_tabnet
}
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

for i, (model_name, y_pred) in enumerate(predictions.items()):
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=axes[i])
    axes[i].set_title(model_name)

plt.tight_layout()
plt.show()

"""#ROC Curve + AUC"""

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

y_test_bin = label_binarize(y_test, classes=np.unique(y_test))
y_score = model_xgb.predict_proba(X_test)

fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(y_test_bin.shape[1]):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure()
for i in range(len(roc_auc)):
    plt.plot(fpr[i], tpr[i], label=f"Class {i} AUC = {roc_auc[i]:.2f}")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("XGBoost ROC Curve")
plt.legend()
plt.show()

"""#Feature Importance"""

import matplotlib.pyplot as plt

importances = model_xgb.feature_importances_
feature_names = X_scaled.columns

plt.figure( )
plt.barh(feature_names, importances)
plt.xlabel("Importance")
plt.title("XGBoost Feature Importance")
plt.show()

"""#Overfitting Check"""

print("Train Accuracy:", model_xgb.score(X_train, y_train))
print("Test Accuracy :", model_xgb.score(X_test, y_test))

"""#XGBoost performed the best with respect to accuracy, precision, recall and F1-score. It also performed well in the confusion matrix with few errors. Moreover, it is robust as shown by the ROC-AUC analysis. Hence, XGBoost is chosen as the model"""