# -*- coding: utf-8 -*-
"""CSE427_colab file[EDA].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6EmPpRb0yQIxG7rfBStQVXwZgf7diKd

### **EDA**
"""

#importing the necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ignore the warning messages
import warnings
warnings.filterwarnings('ignore')

# read dataset from a Google Drive File

file_link = 'https://drive.google.com/file/d/1vacaLMl8VellyUTZM89T9orRFPj8-0zy/view?usp=sharing' # the file access must have to be Public

# get the id part of the file
id = file_link.split("/")[-2]
# print(id)

# creating a new link using the id so that we can easily read the csv file in pandas
new_link = f'https://drive.google.com/uc?id={id}'
print(new_link)
df = pd.read_csv(new_link)

df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"], inplace=True)

# let's look at the first few instances
df.head(10)

df.shape

df.info()

df.describe(include='all')

# Check Unique Values
df.nunique()

# Check for missing values
df.isnull().sum()

#check the cat and num column name
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=np.number).columns.tolist()
print("Categorical Variables:")
print(cat_cols)
print("Numerical Variables:")
print(num_cols)

# Correlation matrix plot
plt.figure(figsize=(8, 6))
correlation_matrix = df.corr(numeric_only=True)
print(correlation_matrix)
plt.matshow(correlation_matrix)
plt.title('Correlation Matrix')
plt.xticks(range(len(correlation_matrix.columns)), correlation_matrix.columns, rotation=90)
plt.yticks(range(len(correlation_matrix.columns)), correlation_matrix.columns)
plt.colorbar()
plt.show()

# Visualize the distribution of the 'Label' variable

print(df.value_counts('labels'))

plt.figure(figsize=(5, 3))
df['labels'].value_counts().plot(kind='bar')
plt.title('Labels Distribution')
plt.xlabel('Labels')
plt.ylabel('Labels Count')
plt.xticks(rotation = 45)
plt.show()

#all feature distribution
df.hist(figsize=(12,10), bins=30)
plt.tight_layout()
plt.show()

FEATURES = [
    "duration (ms)", "danceability", "energy", "loudness",
    "speechiness", "acousticness", "instrumentalness",
    "liveness", "valence", "tempo", "spec_rate"
]
TARGET = "labels"

#box plote-feature per level

fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()

for i, col in enumerate(FEATURES):
    df.boxplot(column=col, by="labels", ax=axes[i], grid=False,patch_artist=True,boxprops=dict(facecolor="lightblue"))
    axes[i].set_title(col)
    axes[i].set_xlabel("Label")
    axes[i].set_ylabel("")
    plt.sca(axes[i])
    plt.title(col)

for j in range(len(FEATURES), len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Feature Box Plots per Label", fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

#histogram , KDE
fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()

for i, col in enumerate(FEATURES):
    axes[i].hist(df[col], bins=50, color="steelblue", alpha=0.7, density=True)
    df[col].plot(kind="kde", ax=axes[i], color="crimson", linewidth=1.5)
    axes[i].set_title(col)
    axes[i].set_xlabel("")

# Turn off the empty last subplot
for j in range(len(FEATURES), len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Feature Distributions (Histogram + KDE)", fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

corr_matrix = df[FEATURES + [TARGET]].corr()

fig, ax = plt.subplots(figsize=(12, 9))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))   # hide upper triangle
sns.heatmap(
    corr_matrix, mask=mask, annot=True, fmt=".2f",
    cmap="coolwarm", center=0, linewidths=0.5,
    square=True, ax=ax
)
ax.set_title("Pearson Correlation Heatmap", fontsize=14)
plt.tight_layout()
plt.show()

#outlier(IQR method)

for col in FEATURES:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < Q1 - 1.5 * IQR) | (df[col] > Q3 + 1.5 * IQR)]
    pct = len(outliers) / len(df) * 100
    print(f"  {col:<22} : {len(outliers):>6,} outliers  ({pct:.2f}%)")

#SKEWNESS & KURTOSIS

sk_kurt = pd.DataFrame({
    "Skewness": df[FEATURES].skew().round(3),
    "Kurtosis": df[FEATURES].kurt().round(3)
})
print(sk_kurt)
# Skewness > |1| , highly skewed , may need log/sqrt transform
# Kurtosis > 3   , heavy tails / outliers

#pairplot
SAMPLE_N = 3000

sample = df[FEATURES + [TARGET]].sample(SAMPLE_N, random_state=42)
sample[TARGET] = sample[TARGET].astype(str)

pair_plot = sns.pairplot(
    sample, hue=TARGET, vars=FEATURES,
    plot_kws={"alpha": 0.4, "s": 10},
    diag_kind="kde", palette="Set2"
)
pair_plot.fig.suptitle("Pairplot — Key Audio Features (sampled)", y=1.01)
plt.show()

#FEATURE–LABEL CORRELATION RANKING

label_corr = df[FEATURES].corrwith(df[TARGET]).abs().sort_values(ascending=False)
print(label_corr.round(4))

fig, ax = plt.subplots(figsize=(9, 5))
label_corr.plot(kind="barh", ax=ax, color="steelblue")
ax.set_title("Absolute Pearson Correlation with Label")
ax.set_xlabel("|r|")
plt.tight_layout()
plt.show()